### ISSUE TITLE
UIs either misleading or partially visible

### ISSUE THREAD

**Issue by Ricky-Tigg** [freeotp/freeotp-android#396] opened 2024-04-02 14:30 UTC
**v:** 2.0.3. **Android v.:** 9. Display | **size** (in mm): 66 x 117 (thus diagonal 5.3'). **resolution:** 1440 x 2560.

Hello.
- _misleading_ | three switching-page-points are exhibited instead of four.

![first_page](https://github.com/freeotp/freeotp-android/assets/26058215/96c1fd76-75d4-49b0-94e6-cdbef5318d1a)

Thus a **page cannot be reached by interacting with the display**. I had the good idea to test whether there are hidden pages using the phone's built-in _move-to-left_ key. Here is the hidden page:

![hidden_page](https://github.com/freeotp/freeotp-android/assets/26058215/81dc94fe-84b5-4000-acc6-81c6425f892d)

- _partially visible_| At last, in the above picture, while a password seems to be set accordingly to a supposed internal rule, there is no element to click in order to validate the operation. That makes the application not operational.

**Comment by joggee-fr** [comment] 2024-06-16 12:41
Duplicate of #349?

**Closed as completed** 2024-07-03 14:32 UTC
