### ISSUE TITLE
FreeOTP crashes when scanning a code that has no label and no issuer.

### ISSUE THREAD

**Issue by AlexHowansky** [freeotp/freeotp-android#200] opened 2018-08-13 14:00 UTC
This is possibly related to issue #172.

I inadvertently created a QR code with no label and no issuer. This code crashes FreeOTP when scanned. The value of the code is as follows:

`otpauth://totp/%3A?issuer=&secret=TEST`

![freeotp_crash](https://user-images.githubusercontent.com/296121/44036399-b339e0f6-9edf-11e8-88d3-f7a8ae57c2fa.png)

**Comment by bostrt** [comment] 2020-07-31 00:03
Hi @AlexHowansky thanks for reporting this. I'm new to the FreeOTP community and taking a look at some outstanding issues, including this one. 

I can confirm the same issue on 1.5 release due to a `StringOutOfBoundsException` from here: https://github.com/freeotp/freeotp-android/blob/v1.5/app/src/main/java/org/fedorahosted/freeotp/Token.java#L75 

It looks like this was fixed in a subsequent commit but is not yet released: https://github.com/freeotp/freeotp-android/commit/e1e37420f5d87359959351f85387d0e9353c133c

I'll run this through a test build to make sure its resolved and let you know.

**Comment by bostrt** [comment] 2020-07-31 04:10
Confirmed this is resolved in e1e3742. Scanning the QR code in this issue simply proceeds with creating token entry in FreeOTP without a crash/error. I'll plan to close this issue out tomorrow but let me know if you have any questions.

**Comment by AlexHowansky** [comment] 2020-07-31 13:18
Thanks for looking into this.

**Comment by bostrt** [comment] 2020-07-31 22:28
*(awaiting permissions to close this out)*

**Comment by bostrt** [comment] 2020-08-07 21:56
Closing this out since its addressed in e1e3742 (just not released yet).

**Closed by bostrt** 2020-08-07 21:56 UTC
